### ISSUE TITLE
Pip-Boy Theme no longer changes color of top bar elements

### ISSUE THREAD

**Issue by loudurdee** [beebls/DeckThemes#24]
the Search icon and the Time-of-Day text are not affected and remain white while all other elements of the top bar change color as expected.

**Comment by suchmememanyskill** [comment]
This is not the repository for opening issues about themes. Please open an issue on the appropriate theme by clicking the 'source code' button on the theme's page

**Comment by loudurdee** [comment]
Apologies, it was late and too many tabs... thanks for your efforts!
