### ISSUE TITLE
On firefox, the glow/blur effect seems to be entirely broken

### ISSUE THREAD

**Issue by suchmememanyskill** [beebls/DeckThemes#6]
![image](https://user-images.githubusercontent.com/38142618/227781968-fb6c5fa1-a9d6-4a7f-9300-60944aa0c7d3.png)

**Comment by beebls** [comment]
This is a firefox moment... I've noticed this for months and cant do anything about it afaik.

Doesn't happen on chrome, and there is no blur here that could be causing it.

**Comment by beebls** [comment]
closing as this is a firefox issue and out of my control
